version: "3.8"

services:
  db:
    image: postgres:15.1
    working_dir: /data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - .:/data
    ports:
      - "5432:5432"
